-- ProjNav VHDL simulation template: or_gate_or_gate_testbanch_vhd_tb.udo
-- You may edit this file after the line that starts with
-- '-- START' to customize your simulation
-- START user-defined simulation commands
